from __future__ import annotations
from typing import Protocol, Tuple


class StoragePort(Protocol):
    def prepare(self, data: bytes) -> Tuple[str, int, str]: ...

    def commit(self, blob_id: str, temp_ref: str) -> None: ...

    def abort(self, temp_ref: str) -> None: ...

    def get(self, blob_id: str) -> Tuple[bytes, int, str]: ...

    def delete(self, blob_id: str) -> None: ...
